api/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.apiOverView, name = 'api-overview'),

    path('project-list/', views.projectList, name = 'project-list'),
    path('project-create/', views.projectCreate, name = 'project-create'),
    path('project-detail/<str:pk>', views.projectDetail, name = 'project-detail'),
    path('project-update/<str:pk>/', views.projectUpdate, name = 'project-update'),
    path('project-update-color/<str:pk>/<str:borderColor>', views.projectColorUpdate),
    path('project-delete/<str:pk>/', views.projectDelete, name = 'project-delete'),

    path('department-list/', views.departmentList, name = 'department-list'),
    path('department-create/', views.departmentCreate, name = 'department-create'),
    path('department-detail/<str:pk>', views.departmentDetail, name = 'department-detail'),
    path('department-update/<str:pk>/', views.departmentUpdate, name = 'department-update'),
    path('department-delete/<str:pk>/', views.departmentDelete, name = 'department-delete'),

    path('states/', views.StatesList.as_view()),
    path('status/', views.StatusList.as_view()),

    path('workpackage/', views.WorkPackageList.as_view(), name = 'WorkPackage-List'),
    path('workpackage-create/', views.WorkPackageCreate.as_view()),
    path('workpackage/<int:pk>/', views.WorkPackageUpdate.as_view()),

    path('workpackage-details/<int:pk>/', views.workpackageDetails),

    path('workpackage-delete/<int:pk>/', views.WorkPackageDelete.as_view()),
    path('update-order/', views.TaskReorder.as_view()),
    path('update-state/', views.updatePackageState),


    path('user-list/', views.userList, name = 'user-list'),
    path('user-profile-list/', views.userDetailList, name = 'user-profile-list'),
    path('project-user_list/<str:pk>/<str:wpk>', views.projectUserList, name = 'project-user_list'),

]

projects/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name = 'home'),
    path('register', views.registrationPage, name = 'register'),
    path('login', views.loginPage, name = 'login'),
    path('logout', views.logoutPage, name = 'logout'),

    path('settings', views.userSettingsPage, name="settings"),   

    path('upload-file/<str:id>', views.upload_view),
]

rope/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('projects.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

api/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class UserType(models.Model):
    type = models.CharField(max_length=255, unique=True)
    
    def __str__(self):
        return str(self.type)

class Project(models.Model):
    title = models.CharField(max_length=255, unique=True)
    description = models.CharField(max_length=255, null=True, default="", blank= True)
    completed = models.BooleanField(default=False, blank= True)
    date_of_creation = models.DateField(auto_now_add=True, null=True, blank= True)
    date_of_start = models.DateField(auto_now_add=False, null=True, blank= True)
    date_of_end = models.DateField(auto_now_add=False, null=True, blank= True)
    responsible = models.ForeignKey(User, null=True, related_name='assignee1', on_delete=models.DO_NOTHING)
    created_by = models.ForeignKey(User, null=True, related_name='creator1', on_delete=models.DO_NOTHING)

    border_color = models.CharField(max_length=8, default="#ffffff")

    def __str__(self):
        return str(self.title)

class State(models.Model):
    title = models.CharField(max_length=255, null=True, blank= True)
    description = models.CharField(max_length=255, null=True, default="", blank= True)
    user_type = models.ForeignKey(UserType, null=True, on_delete=models.DO_NOTHING)
    order = models.IntegerField(null=False, blank= False)
    forward_movement_emp = models.BooleanField(default=True)
    backward_movement_emp = models.BooleanField(default=True)
    forward_movement_manager = models.BooleanField(default=True)
    backward_movement_manager = models.BooleanField(default=True)

    def __str__(self):
        return str(self.title)

class status(models.Model):
    title = models.CharField(max_length=255, null=True, blank= True)
    description = models.CharField(max_length=255, null=True, default="", blank= True)
    user_type = models.ForeignKey(UserType, null=True, on_delete=models.DO_NOTHING)
    state = models.ForeignKey(State, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.title)

class Department(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null = True, blank =True)

    def __str__(self):
        return str(self.title)

class WorkPackage2(models.Model):
    title= models.CharField(max_length=255, null=False, blank= False)
    description = models.CharField(max_length=255, default="", blank= True)
    completed = models.BooleanField(default=False, blank= True)

    date_of_creation = models.DateField(auto_now_add=True, blank= True)

    planned_date_of_start = models.DateField(auto_now_add=False, null=True, blank= True)
    planned_date_of_end = models.DateField(auto_now_add=False, null=True, blank= True)

    duration = models.IntegerField(null=True, blank= True)

    actual_date_of_start = models.DateField(auto_now_add=False, null=True, blank= True)
    actual_date_of_end = models.DateField(auto_now_add=False, null=True, blank= True)

    efforts_actual = models.IntegerField(null=True)
    efforts_planned = models.IntegerField(null=True)

    responsible = models.ForeignKey(User, null=True, related_name='assignee4', on_delete=models.DO_NOTHING)
    created_by = models.ForeignKey(User, null=True, related_name='creator4', on_delete=models.DO_NOTHING)

    project = models.ForeignKey(Project, null=True, on_delete=models.CASCADE)
    
    state = models.ForeignKey(State, null=True, on_delete=models.DO_NOTHING, default = 1)

    inputFrom = models.ForeignKey('self', null=True, related_name='input_from', on_delete=models.DO_NOTHING)
    inputFile = models.FileField(upload_to='documents/', blank=True)

    border_color = models.CharField(max_length=8, default="#f5f5f5")

    def __str__(self):
        return str(self.title)

    class Meta:
        order_with_respect_to = 'responsible'

class WorkPackage3(models.Model):
    
    title= models.CharField(max_length=255, null=False, blank= False)
    description = models.CharField(max_length=255, default="", blank= True)
    completed = models.BooleanField(default=False, blank= True)

    date_of_creation = models.DateField(auto_now_add=True, blank= True)

    planned_date_of_start = models.DateField(auto_now_add=False, null=True, blank= True)
    planned_date_of_end = models.DateField(auto_now_add=False, null=True, blank= True)

    duration = models.IntegerField(null=True, blank= True)

    actual_date_of_start = models.DateField(auto_now_add=False, null=True, blank= True)
    actual_date_of_end = models.DateField(auto_now_add=False, null=True, blank= True)

    efforts_actual = models.IntegerField(null=True)
    efforts_planned = models.IntegerField(null=True)

    responsible = models.ForeignKey(User, null=True, related_name='assignee5', on_delete=models.DO_NOTHING)
    created_by = models.ForeignKey(User, null=True, related_name='creator5', on_delete=models.DO_NOTHING)

    project = models.ForeignKey(Project, null=True, on_delete=models.CASCADE)
    parentPackage = models.ForeignKey(WorkPackage2, null=True, on_delete=models.CASCADE)
    
    state = models.ForeignKey(State, null=True, on_delete=models.DO_NOTHING, default = 1)

    emp_status = models.ForeignKey(status, null=True, related_name='employee_status', on_delete=models.DO_NOTHING)
    manager_status = models.ForeignKey(status, null=True, related_name='manager_status', on_delete=models.DO_NOTHING, default = 4)

    inputFrom = models.ForeignKey('self', null=True, related_name='input_from', on_delete=models.DO_NOTHING)
    inputFile = models.FileField(upload_to='documents/', blank=True)

    border_color = models.CharField(max_length=8, default="#f5f5f5")

    def __str__(self):
        return str(self.title)

    class Meta:
        order_with_respect_to = 'responsible'


class UserProfileDetail(models.Model):
    
    user = models.OneToOneField(User, null = True, blank = True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null = True)
    phone = models.CharField(max_length=200, null = True)
    email = models.CharField(max_length=200, null = True)
    profile_pic = models.ImageField(default="default_profile.png", null = True, blank = True)
    department = models.ForeignKey(Department, null=True, on_delete=models.CASCADE)
    user_type = models.ForeignKey(UserType, null=True, on_delete=models.DO_NOTHING, default=1)
    date_created = models.DateField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.user)

def create_profile(sender, instance, created, **kwargs):
    if created:
        new_user = UserProfileDetail.objects.create(user = instance, name = instance.first_name +" "+ instance.last_name)
               
        print("Profile Created!", instance.first_name)

post_save.connect(create_profile, sender = User)

projects/models.py
from django.db import models

# Create your models here.

projects/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from api.models import *

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        
class ProjectTableForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'onkeypress':'return enterKeyPress(event)'})
        }

class UserProfileDetailForm(forms.ModelForm):
    class Meta:
        model = UserProfileDetail
        fields = '__all__'
        exclude = ['user', 'date_created', 'date_created']


        widgets = {
            'profile_pic': forms.FileInput(attrs={'name':'profile_pic','class': 'form-control-file','placeholder':'Profile Photo...','id':'id_profile_pic', 'style':'width:85%!important'}),
        }

class PositionForm(forms.Form):
    position = forms.CharField()

class WorkPackageDetailsForm(forms.ModelForm):
    class Meta:
        model = WorkPackage3
        fields = ['title', 'description', 'emp_status', 'efforts_planned']

    def __init__(self, *args, **kwargs):
        super(WorkPackageDetailsForm, self).__init__(*args, **kwargs)
        self.fields['emp_status'].queryset = status.objects.filter(user_type=1, state = 2)
    
class WorkPackageCreationForm(forms.ModelForm):
    class Meta:
        model = WorkPackage3
        fields = ['title', 'parentPackage', 'inputFrom']

class Workpackage3DocumentForm(forms.ModelForm):
    class Meta:
        model = WorkPackage3
        fields = ['inputFile']

api/views/project_views.py
from django.shortcuts import render

from api.models import *
from api.serializer import *

from rest_framework.decorators import api_view
from rest_framework.response import Response

@api_view(['GET'])
def apiOverView(request):
    api_urls={
        'Projects': '/project-list/'
    }
    return Response(api_urls)

@api_view(['GET'])
def projectList(request):
    project = Project.objects.all()
    serializer = ProjectSerializer(project, many = True)
    return Response(serializer.data)

@api_view(['POST'])
def projectCreate(request):
    serializer = ProjectSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save()

    return Response(serializer.data)
    
@api_view(['GET'])
def projectDetail(request, pk):
    project = Project.objects.get(id = pk)
    serializer = ProjectSerializer(project, many = False)

    return Response(serializer.data)

@api_view(['POST'])
def projectUpdate(request, pk):
    project = Project.objects.get(id = pk)
    serializer = ProjectSerializer(instance = project, data = request.data)

    if serializer.is_valid():
        serializer.save()

    return Response(serializer.data)

@api_view(['POST'])
def projectColorUpdate(request, pk, borderColor):
    project = Project.objects.get(id = pk)
    project.border_color = "#"+borderColor
    project.save()
    WorkPackage.objects.filter(project_Id = pk).update(border_color = "#"+borderColor)
    return Response('Success')

@api_view(['DELETE'])
def projectDelete(request, pk):
    project = Project.objects.get(id = pk)
    project.delete()

    return Response('Item Deleted Successsfully')

projects/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views.generic import View

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .decorators import *

from .forms import *

@login_required(login_url='login')
#@allowed_users(allowed_roles = ['admin'])
def home(request):
    context = {}
    if request.user.userprofiledetail.user_type.id == 2:
        createPackageForm = WorkPackageCreationForm()
        context = {'form': createPackageForm}
    uploadFileForm = Workpackage3DocumentForm()
    context['uploadForm'] = uploadFileForm
        
    return render(request, 'projects/index.html', context)

@unauthenticated_user
def registrationPage(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for '+ user)
            return redirect('login')

    context = {'form':form}
    return render(request, 'registration.html', context)

@unauthenticated_user
def loginPage(request):
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username = username, password = password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Username or Password is incorrect!')
    context={}
    return render(request, 'login.html', context)

def logoutPage(request):
    
    logout(request)
    context={}
    return render(request, 'login.html', context)


def userSettingsPage(request):
    user = request.user.userprofiledetail
    
    if request.method == 'POST':
        form = UserProfileDetailForm(request.POST, request.FILES, instance=user)
        if form.is_valid:
            form.save()

    form = UserProfileDetailForm(instance=user)
    context = {'form':form}

    return render(request, "projects/settings.html", context)

def upload_view(request, id):
    workPackage3 = WorkPackage3.objects.get(id = id)
    if request.method == 'POST':
        form = Workpackage3DocumentForm(data=request.POST, files=request.FILES, instance=workPackage3)
        print(request.FILES)
    if form.is_valid():
        form.save()
        print('valid form')
    else:
        print('invalid form')
        print(form.errors)

    return HttpResponse('/ingest/')

templates/projects/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Add Project
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.structure.min.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.theme.min.css"/>
{% endblock %}

{% block subtitlerow1 %}
  Kanban Board
{% endblock %}
{% load crispy_forms_tags %}
{% block subtitlerow2 %}
{% if request.user.userprofiledetail.user_type.id == 2 %}
<div class="row">
  <div class="col">
    <div id="accordion">
      <button class="btn collapsed btn-info" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        New Package <i class="fa fa-plus" aria-hidden="true"></i>
      </button>
      <div id="collapseTwo" class="collapse" aria-labelledby="newPackage" data-parent="#accordion">
        <div class="mt-1 p-2">
          <form id="create_package_form" action='' method='POST'>
            {% csrf_token %}
            <div class="row">
              <div class="col-lg-5 col-md-12">
                {{form.title|as_crispy_field}}
              </div>
              <div class="col-lg-5 col-md-12">
                {{form.parentPackage|as_crispy_field}}
              </div>
              <div class="col-lg-5 col-md-12">
                {{form.inputFrom|as_crispy_field}}
              </div>
              <div class="col-lg-2 col-md-12 d-flex align-items-center mt-lg-3">
                <input type="button" class="align-bottom btn btn-success" id="createPackage" value="Create"/>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

{% block content %}
<!-- Task Cards -->
    <div class="lists mt-1 border-top" id="taskCardContainer">
      
    </div>
<!--/ Task Cards -->


{% endblock content %}

{% block javaScriptBlock %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  <script src="{% static 'js/kanban/kanban.js' %}"></script>
  <script src="{% static 'js/kanban/card_form.js' %}"></script>
  <script src="{% static 'js/kanban/input_File_details.js' %}"></script>
{% endblock %}

templates/projects/settings.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
    .input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		
</style>
{% endblock %}

{% block title %}
  Add Project
{% endblock %}


{% block subtitlerow1 %}
  <h5>Projects</h5>
{% endblock %}
{% block subtitlerow2 %}

{% endblock %}

{% block content %}
<div id="cover-spin"></div>



<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<a class="btn btn-warning" href="{% url 'home' %}"> &#8592; Back to Profile</a>
			<hr>
			<h3 style="text-align: center">Account Settings</h3>
			<hr>
			<img class="profile-pic" src="{{request.user.userprofiledetail.profile_pic.url}}" >
		</div>
	</div>
	<div class="col-md-6">
		<div class="card card-body">
			
			<form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-group mb-2">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                    </div>
                    {{ form.name }}
                </div>

                <div class="input-group mb-2">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fa fa-phone"></i></span>
                    </div>
                    {{ form.phone }}
                </div>
                <div class="input-group mb-2">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                    </div>
                    {{ form.email }}
                </div>
                <div class="input-group mb-2">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fa fa-pencil-square"></i></span>
                    </div>
                    {{ form.department }}
                </div>
                <div class="input-group mb-2">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fa fa-pencil-square"></i></span>
                    </div>
                    {{ form.user_type }}
                </div>
                <div class="input-group mb-2">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fa fa-user-circle"></i></span>
                    </div>
                    {{ form.profile_pic }}
                </div>

				
		
			    <input class="btn btn-success" type="submit" value="Update Information" name="Update Information">
			</form>
		</div>
    </div>
</div>



{% endblock content %}

{% block javaScriptBlock %}
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[2].placeholder='Name...';
    form_fields[3].placeholder='Phone...';
    form_fields[4].placeholder='Email...';
    

    for (var i=1; i < form_fields.length-1; i++){
        form_fields[i].className += 'form-control'
    }
    
    $('#id_department').addClass('form-control')
    $('#id_user_type').addClass('form-control')
</script>
  <!--<script src="{% static 'js/.js' %}"></script>-->
{% endblock %}